version: '3.7'

services:
    microservice:
        build:
            context: .
        image: bot-portugal-news
        container_name: bot-portugal-news
        restart: unless-stopped

        command: ["python3", "main.py"]