KEY_SEARCH_LENGTH_CHARS = 50
COUNT_UNIQUE_MESSAGES = 1000
TIMEOUT = 4
MESSAGE_SIMILARITY_THRESHOLD = 0.7
MAX_NUMBER_TAKEN_MESSAGES = 20
REPEAT_REQUESTS = 5
MINIMUM_NUMBER_KEYWORDS = 20
MAX_VIDEO_SIZE_MB = 50
MAX_COUNT_KEYWORDS = 5
WEIGHT_KEYWORDS_THRESHOLD = 2
TARGET_LANGUAGE = 'pt'

TELEGRAM_MAX_LENGTH_MESSAGE = 1000
FACEBOOK_MAX_LENGTH_MESSAGE = 6000
INSTAGRAM_MAX_LENGTH_MESSAGE = 5000
