KEY_SEARCH_LENGTH_CHARS = 50
COUNT_UNIQUE_MESSAGES = 1000
TIMEOUT = 4
MESSAGE_SIMILARITY_THRESHOLD = 0.7
MAX_NUMBER_TAKEN_MESSAGES = 20
REPEAT_REQUESTS = 5
MINIMUM_NUMBER_KEYWORDS = 17
MAX_VIDEO_SIZE_MB = 100
MAX_COUNT_KEYWORDS = 5
WEIGHT_KEYWORDS_THRESHOLD = 2

TELEGRAM_MAX_LENGTH_MESSAGE = 1000
FACEBOOK_MAX_LENGTH_MESSAGE = 5000
INSTAGRAM_MAX_LENGTH_MESSAGE = 5000
