name: Bot Schedule

concurrency:
  group: bot-schedule
  cancel-in-progress: false

on:
  # schedule:
  #   - cron: '0 */2 * * *'
  workflow_dispatch:
    inputs:
      log_level:
        description: 'Logging level (DEBUG, INFO, WARNING, ERROR, CRITICAL)'
        required: false
        default: 'DEBUG'
        type: choice
        options:
          - DEBUG
          - INFO
          - WARNING
          - ERROR
          - CRITICAL

jobs:
  bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check Facebook token
        run: |
          response=$(curl -s "https://graph.facebook.com/v18.0/me?access_token=${{ secrets.FACEBOOK_ACCESS_TOKEN }}")
          if echo "$response" | grep -q "error"; then
            echo "Facebook token is invalid: $response"
            exit 1
          fi
          echo "Facebook token is valid"
      - name: Setup Python environment
        uses: ./.github/actions/setup-python-env
      - name: Create logs directory
        run: mkdir -p logs
      - name: Run bot
        run: python main.py
        timeout-minutes: 10
        continue-on-error: true
        env:
          TELEGRAM_TOKEN_BOT: ${{ secrets.TELEGRAM_TOKEN_BOT }}
          TELEGRAM_API_ID: ${{ secrets.TELEGRAM_API_ID }}
          TELEGRAM_API_HASH: ${{ secrets.TELEGRAM_API_HASH }}
          FACEBOOK_ACCESS_TOKEN: ${{ secrets.FACEBOOK_ACCESS_TOKEN }}
          LOG_LEVEL: ${{ github.event_name == 'schedule' && 'WARNING' || inputs.log_level || 'DEBUG' }}
      - name: Notify Telegram on failure
        if: failure()
        run: |
          curl -s -X POST 'https://api.telegram.org/bot${{ secrets.TOKEN_BOT }}/sendMessage' \
            -d chat_id=-1002178707665 \
            -d parse_mode=Markdown \
            -d text="❌ *CI бота упал!* [Открыть логи CI](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})"
      - name: Upload logs
        uses: actions/upload-artifact@v4
        with:
          name: parser-logs
          path: logs/
          retention-days: 5
          compression-level: 0
